Update cyber security base deploy script

diff --git a/.github/workflows/upload-cyber-security-base-image.yml b/.github/workflows/upload-cyber-security-base-image.yml
--- a/.github/workflows/upload-cyber-security-base-image.yml
+++ b/.github/workflows/upload-cyber-security-base-image.yml
@@ -21,20 +21,28 @@ jobs:
           echo ::set-env name=RUST_CLI_NAME::${RUST_CLI_NAME}
           echo ::set-env name=RUST_CLI_VER::${RUST_CLI_VER}
           echo ::set-env name=RUST_CLI_URL::${RUST_CLI_URL}
-      - uses: RafikFarhad/push-to-gcr-github-action@v1
-        with:
-          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
-          registry: eu.gcr.io
-          project_name: moocfi-public
-          image_name: tmc-sandbox-cyber-security-base
-          image_tag: ${{ env.RUST_CLI_VER }}
-          context: ./cyber-security-base
-          dockerfile: ./cyber-security-base/Dockerfile
-      - uses: RafikFarhad/push-to-gcr-github-action@v1
-        with:
-          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
-          registry: eu.gcr.io
-          project_name: moocfi-public
-          image_name: tmc-sandbox-cyber-security-base
-          context: ./cyber-security-base
-          dockerfile: ./cyber-security-base/Dockerfile
+      - name: Authenticate to Google Cloud
+        env:
+          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
+        run: |
+          echo Authenticating to Google Cloud
+          echo $GCLOUD_SERVICE_KEY | python -m base64 -d > /tmp/key.json
+          gcloud auth activate-service-account --key-file=/tmp/key.json
+          if gcloud auth configure-docker -q; then
+              echo "Authenticated to Google Cloud..."
+          else
+              echo "Authentication to Google Cloud failed. Exiting..."
+              exit 1
+          fi
+      - name: Building image
+        run: |
+          cd tmc-langs-rust
+          docker build . -t "eu.gcr.io/moocfi-public/tmc-sandbox-cyber-security-base:${{ env.RUST_CLI_VER }}" --build-arg "RUST_CLI_URL=${{ env.RUST_CLI_URL }}"
+          cd ..
+      - name: Pushing image
+        run: |
+          cd tmc-langs-rust
+          docker push "eu.gcr.io/moocfi-public/tmc-sandbox-cyber-security-base:${{ env.RUST_CLI_VER }}"
+          docker tag "eu.gcr.io/moocfi-public/tmc-sandbox-cyber-security-base:${{ env.RUST_CLI_VER }}" "eu.gcr.io/moocfi-public/tmc-sandbox-cyber-security-base:latest"
+          docker push "eu.gcr.io/moocfi-public/tmc-sandbox-cyber-security-base:latest"
+          cd ..
